### ISSUE TITLE
Error in the QA-report

### ISSUE THREAD

**Issue by tmsMedcom** [hl7dk/dk-core#89] opened 2023-05-09 10:22 UTC
Currently we have the following error in the QA-report. We are waiting on HL7 to do some fixes, before we can solve it. Milestone is set to the next release.

"This code DOES exist and is published by IEEE. But somehow the code system tooling missed it along the way

ERROR: Bundle/ContinuaBundleWithDevice: Bundle.entry[7].resource/*Observation/BloodPressureStatus.Poul.133527*/.code.coding[0]: Local Error: Resolved system urn:iso:std:iso:11073:10101 (v2.0.1), but the definition is not complete. Server Error: The code "8410608" is not valid in the system urn:iso:std:iso:11073:10101; The code provided (urn:iso:std:iso:11073:10101#8410608) is not valid in the value set 'All codes known to the system' (from http://tx.fhir.org/r4) for 'urn:iso:std:iso:11073:10101#8410608' (0 uses)"

**Comment by jacand** [comment] 2023-05-09 12:13
Progress can be monitored on Zulip in this thread: https://chat.fhir.org/#narrow/stream/179202-terminology/topic/Missing.20MDC.20code
Status as of today: A new RTMMS terminology server for the IEEE codes was launched last week here http://rtmms.nist.gov/ and I can confirm that the missing code has been added to this server. According to the Zulip thread, Grahame is working with Michael Faughn to synchronize the FHIR terminology service with this new server.  So at this point, we are waiting for them to do some background magic.

**Comment by jacand** [comment] 2023-08-31 10:42
I have poked Grahame and Michael on Zulip, asking for progress. Apparently the thread died in May and no progress happened since then...

**Comment by jacand** [comment] 2023-09-01 19:11
The solution should be in the pipes:
https://github.com/FHIR/packages/pull/14
https://chat.fhir.org/#narrow/stream/179202-terminology/topic/Missing.20MDC.20code

**Comment by jacand** [comment] 2023-10-23 20:07
@tmsMedcom @jkiddo Poked Grahame again on Zulip. He answered that he will try to get it done this week.
https://chat.fhir.org/#narrow/stream/179202-terminology/topic/Missing.20MDC.20code

**Comment by tmsMedcom** [comment] 2023-11-30 14:57
@jacand Do you know if the issue has been fixed?

**Comment by jacand** [comment] 2023-11-30 15:12
As long as it is not critical and things blow up, I would just wait it out. Perhaps remind him again early next year. But this situation confirms the need to ensure that terminology hosting is properly funded and governed - as we discussed on the meeting last week regarding Snomed translations...

**Comment by tmsMedcom** [comment] 2024-03-26 14:24
@jacand is there any news around this issue?

**Comment by jacand** [comment] 2024-04-02 10:29
@tmsMedcom As far as I can tell, it has been resolved. Can you confirm that the error has disappeared (and close the issue if that is the case)?
The following lookup yields a result, and the problem was that it didn't:
https://tx.fhir.org/r4/CodeSystem/$lookup?system=urn:iso:std:iso:11073:10101&code=8410608

**Comment by tmsMedcom** [comment] 2024-04-02 12:44
@jacand Great, it seems to be solved in the latest build of the IG.

**Closed** 2024-04-23 08:20 UTC
Labels: error handling
